# A blueprint for a Django app on Render.
services:
  - type: web
    name: microsoft_2025_platform
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn microsoft_2025_platform.wsgi:application"
    plan: free # ou 'pro' ou 'starter' conforme sua necessidade
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: microsoft_2025_platform_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

  - type: worker
    name: django-migrations
    env: python
    buildCommand: "echo 'No build command for worker'"
    startCommand: "python manage.py migrate --noinput"
    plan: free # ou 'pro' ou 'starter' conforme sua necessidade
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: microsoft_2025_platform_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

  - type: database
    name: microsoft_2025_platform_db
    databaseName: microsoft_2025_db
    plan: free # ou 'pro' ou 'starter' conforme sua necessidade
    